FROM easybuilders/base:centos7-eb4.2.1
# install software & accompanying modules
# use /easybuild for everything that should persist in the container (software, modules and sources)
# everything else goes in /scratch, which will be cleaned out
RUN eb --prefix /scratch --installpath /easybuild GCC-9.3.0.eb --robot --trace \
  # clean up everything in /scratch
  && rm -rf /scratch/*
